# Site settings
title: Spaceship landing site
email: znurgl@gmail.com
author: Gergo Bakos
keywords: "Java, Scala, AWS, Spring, Computer Science"
baseurl: ""
url: "https://znurgl.github.io"
twitter_username: znurgl
github_username: znurgl
disqus_shortname: znurgl
favicon: "/images/favicon.ico"
aboutme: Hi, this is Gergo. JVM and big data developer.
aboutme_photo: http://i.imgur.com/jZshyJD.jpg
locale: en_US

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: kramdown
# highlighter: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-seo-tag, jekyll-paginate]

paginate: 5
