# Site settings
title: (blog [scala clojure computers])
email: znurgl@gmail.com
author: Greg Bakos
keywords: "Scala, Clojure, AWS, Cluster, Programming"
baseurl: ""
url: "http://znurgl.net"
twitter_username: znurgl
github_username:  znurgl
disqus_shortname: znurgl
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Greg, a Scala developer and Clojure enthusiast.
aboutme_photo: http://i.imgur.com/jZshyJD.jpg
locale: en_US


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: kramdown
# highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge

gems: [jekyll-seo-tag, jekyll-paginate]

paginate: 5
